import { useEffect, useRef } from 'react'
import TokenLogo from './TokenLogo'
import { Icon } from './Icons'
import { formatDate, short } from './resultUtils'

export default function ReceiptModal({ result, onClose }) {
  const dialogRef = useRef(null)
  const multipleTransfers = Number(result.transferCount || 0) > 1

  useEffect(() => {
    dialogRef.current?.focus()
    const onKey = (event) => {
      if (event.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  const receiptRows = [
    ['Recipient', short(result.recipient)],
    [multipleTransfers ? 'Latest transfer' : 'Date', formatDate(result.blockTime)],
    ['Network', result.network],
    ['Verified transfers', String(result.transferCount || 1)],
    [multipleTransfers ? 'Latest transaction' : 'Transaction', short(result.transactionSignature)],
    ['Distribution wallet', short(result.sourceWallet)],
    ['Tracked mint', short(result.tokenMint)],
  ]

  function download() {
    const canvas = document.createElement('canvas')
    canvas.width = 900
    canvas.height = 1280
    const ctx = canvas.getContext('2d')
    ctx.fillStyle = '#fff'
    ctx.fillRect(0, 0, 900, 1280)
    ctx.fillStyle = '#101828'
    ctx.textAlign = 'center'
    ctx.font = 'bold 42px Inter, sans-serif'
    ctx.fillText('$ANSEM Wallet Receipt', 450, 100)
    ctx.fillStyle = '#16A36A'
    ctx.font = 'bold 28px Inter, sans-serif'
    ctx.fillText('Distribution confirmed', 450, 170)
    ctx.fillStyle = '#101828'
    ctx.font = 'bold 56px Inter, sans-serif'
    ctx.fillText(`${result.amountReceived} $ANSEM`, 450, 290)
    ctx.textAlign = 'left'

    receiptRows.forEach(([label, value], index) => {
      const y = 390 + index * 105
      ctx.fillStyle = '#667085'
      ctx.font = '22px Inter'
      ctx.fillText(label, 90, y)
      ctx.fillStyle = '#101828'
      ctx.font = '24px monospace'
      ctx.fillText(value, 90, y + 38)
    })

    ctx.fillStyle = '#667085'
    ctx.font = '22px Inter'
    ctx.textAlign = 'center'
    ctx.fillText('Generated by $ANSEM Wallet Checker', 450, 1210)

    const link = document.createElement('a')
    link.download = 'ansem-wallet-receipt.png'
    link.href = canvas.toDataURL('image/png')
    link.click()
  }

  return (
    <div className="modal-backdrop" role="presentation">
      <div
        className="receipt-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="receipt-title"
        tabIndex="-1"
        ref={dialogRef}
      >
        <button className="modal-close" onClick={onClose} aria-label="Close receipt">
          <Icon name="close" />
        </button>
        <div className="receipt-preview">
          <div className="receipt-brand">
            <TokenLogo compact />
            <strong id="receipt-title">$ANSEM Wallet Receipt</strong>
          </div>
          <p className="confirmed"><Icon name="check" />Distribution confirmed</p>
          <strong className="receipt-amount">{result.amountReceived} $ANSEM</strong>
          {receiptRows.map(([label, value]) => (
            <p className="receipt-row" key={label}>
              <span>{label}</span>
              <b>{value}</b>
            </p>
          ))}
          <small>Generated by $ANSEM Wallet Checker</small>
        </div>
        <button className="primary-btn download" onClick={download}>Download PNG</button>
      </div>
    </div>
  )
}
