import { useEffect, useRef, useState } from 'react'
import TokenLogo, { TOKEN_LOGO_URL } from './TokenLogo'
import { Icon } from './Icons'
import { formatDate, short } from './resultUtils'
import './ReceiptActions.css'

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const image = new Image()
    image.onload = () => resolve(image)
    image.onerror = () => reject(new Error('The token logo could not be loaded.'))
    image.src = src
  })
}

function drawImageCover(ctx, image, x, y, width, height) {
  const imageRatio = image.naturalWidth / image.naturalHeight
  const targetRatio = width / height
  let sourceX = 0
  let sourceY = 0
  let sourceWidth = image.naturalWidth
  let sourceHeight = image.naturalHeight

  if (imageRatio > targetRatio) {
    sourceWidth = image.naturalHeight * targetRatio
    sourceX = (image.naturalWidth - sourceWidth) / 2
  } else {
    sourceHeight = image.naturalWidth / targetRatio
    sourceY = (image.naturalHeight - sourceHeight) / 2
  }

  ctx.drawImage(image, sourceX, sourceY, sourceWidth, sourceHeight, x, y, width, height)
}

function canvasToBlob(canvas) {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) resolve(blob)
      else reject(new Error('The receipt image could not be created.'))
    }, 'image/png')
  })
}

function downloadFile(file) {
  const url = URL.createObjectURL(file)
  const link = document.createElement('a')
  link.download = file.name
  link.href = url
  link.click()
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export default function ReceiptModal({ result, onClose }) {
  const dialogRef = useRef(null)
  const [sharing, setSharing] = useState(false)
  const multipleTransfers = Number(result.transferCount || 0) > 1

  useEffect(() => {
    dialogRef.current?.focus()
    const onKey = (event) => {
      if (event.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  const receiptRows = [
    ['Recipient', short(result.recipient)],
    [multipleTransfers ? 'Latest transfer' : 'Date', formatDate(result.blockTime)],
    ['Network', result.network],
    ['Verified transfers', String(result.transferCount || 1)],
    [multipleTransfers ? 'Latest transaction' : 'Transaction', short(result.transactionSignature)],
    ['Distribution wallet', short(result.sourceWallet)],
    ['Tracked mint', short(result.tokenMint)],
  ]

  const draftTweet = [
    `Just verified a ${result.amountReceived} $ANSEM distribution on-chain with the $ANSEM Wallet Checker.`,
    'Transparent. Verifiable. Solana Mainnet.',
    '$ANSEM @blknoiz06',
  ].join('\n\n')

  async function createReceiptFile() {
    const logo = await loadImage(TOKEN_LOGO_URL)
    const canvas = document.createElement('canvas')
    canvas.width = 900
    canvas.height = 1280
    const ctx = canvas.getContext('2d')

    if (!ctx) throw new Error('Image generation is unavailable in this browser.')

    ctx.fillStyle = '#fff'
    ctx.fillRect(0, 0, 900, 1280)

    ctx.save()
    ctx.beginPath()
    ctx.arc(150, 94, 43, 0, Math.PI * 2)
    ctx.clip()
    drawImageCover(ctx, logo, 107, 51, 86, 86)
    ctx.restore()

    ctx.strokeStyle = '#E4E7EC'
    ctx.lineWidth = 2
    ctx.beginPath()
    ctx.arc(150, 94, 43, 0, Math.PI * 2)
    ctx.stroke()

    ctx.fillStyle = '#101828'
    ctx.textAlign = 'left'
    ctx.font = 'bold 42px Inter, sans-serif'
    ctx.fillText('$ANSEM Wallet Receipt', 220, 109)

    ctx.fillStyle = '#16A36A'
    ctx.textAlign = 'center'
    ctx.font = 'bold 28px Inter, sans-serif'
    ctx.fillText('✓  Distribution confirmed', 450, 190)

    ctx.fillStyle = '#101828'
    ctx.font = 'bold 58px Inter, sans-serif'
    ctx.fillText(`${result.amountReceived} $ANSEM`, 450, 305)

    receiptRows.forEach(([label, value], index) => {
      const y = 410 + index * 105

      ctx.strokeStyle = '#E4E7EC'
      ctx.lineWidth = 1
      ctx.beginPath()
      ctx.moveTo(90, y - 38)
      ctx.lineTo(810, y - 38)
      ctx.stroke()

      ctx.fillStyle = '#667085'
      ctx.textAlign = 'left'
      ctx.font = '22px Inter, sans-serif'
      ctx.fillText(label, 90, y)

      ctx.fillStyle = '#101828'
      ctx.textAlign = 'right'
      ctx.font = '24px ui-monospace, SFMono-Regular, Menlo, monospace'
      ctx.fillText(value, 810, y)
    })

    ctx.strokeStyle = '#E4E7EC'
    ctx.beginPath()
    ctx.moveTo(90, 1115)
    ctx.lineTo(810, 1115)
    ctx.stroke()

    ctx.fillStyle = '#344054'
    ctx.textAlign = 'center'
    ctx.font = '22px Inter, sans-serif'
    ctx.fillText('Generated by $ANSEM Wallet Checker', 450, 1170)

    ctx.fillStyle = '#667085'
    ctx.font = '18px Inter, sans-serif'
    ctx.fillText('Read-only verification • No wallet connection required', 450, 1210)
    ctx.fillText('ansem-wallet-checker.ansemverify.workers.dev', 450, 1245)

    const blob = await canvasToBlob(canvas)
    return new File([blob], 'ansem-wallet-receipt.png', { type: 'image/png' })
  }

  async function shareReceipt() {
    setSharing(true)

    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(draftTweet).catch(() => {})
      }

      const file = await createReceiptFile()
      const supportsNativeFileShare =
        typeof navigator.share === 'function'
        && (typeof navigator.canShare !== 'function' || navigator.canShare({ files: [file] }))

      if (supportsNativeFileShare) {
        await navigator.share({ files: [file] })
        return
      }

      downloadFile(file)
      window.alert('The receipt image was saved. Open X, attach it, and paste the copied caption.')
    } catch (error) {
      if (error?.name !== 'AbortError') {
        console.error('Receipt sharing failed', error)
        window.alert('The receipt image could not be shared. Please try again.')
      }
    } finally {
      setSharing(false)
    }
  }

  return (
    <div className="modal-backdrop" role="presentation">
      <div
        className="receipt-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="receipt-title"
        tabIndex="-1"
        ref={dialogRef}
      >
        <button className="modal-close" onClick={onClose} aria-label="Close receipt">
          <Icon name="close" />
        </button>
        <div className="receipt-preview">
          <div className="receipt-brand">
            <TokenLogo compact />
            <strong id="receipt-title">$ANSEM Wallet Receipt</strong>
          </div>
          <p className="confirmed"><Icon name="check" />Distribution confirmed</p>
          <strong className="receipt-amount">{result.amountReceived} $ANSEM</strong>
          {receiptRows.map(([label, value]) => (
            <p className="receipt-row" key={label}>
              <span>{label}</span>
              <b>{value}</b>
            </p>
          ))}
          <small>Generated by $ANSEM Wallet Checker</small>
        </div>

        <button className="primary-btn share-x" onClick={shareReceipt} disabled={sharing}>
          <span className="x-mark" aria-hidden="true">X</span>
          {sharing ? 'Preparing image…' : 'Share to X'}
        </button>
      </div>
    </div>
  )
}
